
services:
  nats-server:
    image: nats:alpine3.20
    ports:
      - "8222:8222"
    networks:
      - app-network

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: Dockerfile
      target: final-prod
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
    depends_on:
      - nats-server
    networks:
      - app-network

  product-services:
    build:
      context: ./product-ms
      dockerfile: Dockerfile
      target: final-prod
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=sqlite.db
    depends_on:
      - nats-server
    networks:
      - app-network

  orders-db:
    container_name: orders-database
    image: postgres:16.4-alpine3.20
    restart: always
    environment:
      - POSTGRES_USER=marlon
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb
    volumes:
      - orders-ms_db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-network

  orders-ms:
    container_name: orders-microservice
    build:
      context: ./orders-ms
      dockerfile: Dockerfile
      target: final-prod
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgres://marlon:123456@orders-db:5432/ordersdb
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=3002
    depends_on:
      - orders-db
      - nats-server
    networks:
      - app-network

volumes:
  orders-ms_db-data:
    external: true

networks:
  app-network:
